path = r'C:\Users\ryanl\OneDrive\Desktop\Kalshi Bot\kalshi_client.py'

code = []
code.append('import requests\n')
code.append('import base64\n')
code.append('from cryptography.hazmat.primitives import hashes, serialization\n')
code.append('from cryptography.hazmat.primitives.asymmetric import padding\n')
code.append('from datetime import datetime, timezone\n')
code.append('\n')
code.append('class KalshiClient:\n')
code.append('    BASE_URL = "https://api.elections.kalshi.com/trade-api/v2"\n')
code.append('\n')
code.append('    def __init__(self, config):\n')
code.append('        self.config = config\n')
code.append('        self.session = requests.Session()\n')
code.append('        self.session.headers.update({"Accept": "application/json", "Content-Type": "application/json"})\n')
code.append('\n')
code.append('    def _sign_request(self, method, path):\n')
code.append('        timestamp = str(int(datetime.now(timezone.utc).timestamp() * 1000))\n')
code.append('        message = timestamp + method.upper() + path\n')
code.append('        try:\n')
code.append('            pk = self.config.KALSHI_API_PRIVATE_KEY\n')
code.append('            pk = pk.replace("\\\\n", "\\n")\n')
code.append('            if not pk.startswith("-----"):\n')
code.append('                pk = "-----BEGIN RSA PRIVATE KEY-----\\n" + pk + "\\n-----END RSA PRIVATE KEY-----"\n')
code.append('            private_key = serialization.load_pem_private_key(pk.encode(), password=None)\n')
code.append('            signature = private_key.sign(message.encode(), padding.PKCS1v15(), hashes.SHA256())\n')
code.append('            return {\n')
code.append('                "KALSHI-ACCESS-KEY": self.config.KALSHI_API_KEY_ID,\n')
code.append('                "KALSHI-ACCESS-TIMESTAMP": timestamp,\n')
code.append('                "KALSHI-ACCESS-SIGNATURE": base64.b64encode(signature).decode()\n')
code.append('            }\n')
code.append('        except Exception as e:\n')
code.append('            print("Signing error: " + str(e))\n')
code.append('            return {}\n')
code.append('\n')
code.append('    def get_markets(self, limit=10):\n')
code.append('        path = "/markets"\n')
code.append('        try:\n')
code.append('            resp = self.session.get(self.BASE_URL + path, headers=self._sign_request("GET", path), params={"status": "open", "limit": limit * 3}, timeout=15)\n')
code.append('            resp.raise_for_status()\n')
code.append('            markets = resp.json().get("markets", [])\n')
code.append('            result = [self._normalize(m) for m in markets if m]\n')
code.append('            result = [m for m in result if m]\n')
code.append('            print("Found " + str(len(result)) + " markets")\n')
code.append('            return result[:limit]\n')
code.append('        except Exception as e:\n')
code.append('            print("Error fetching markets: " + str(e))\n')
code.append('            return self._demo_markets()[:limit]\n')
code.append('\n')
code.append('    def _normalize(self, raw):\n')
code.append('        try:\n')
code.append('            yes_price = raw.get("yes_ask_dollars") or raw.get("yes_bid_dollars") or raw.get("last_price_dollars") or "0.5"\n')
code.append('            yes_price = float(yes_price)\n')
code.append('            if yes_price > 1:\n')
code.append('                yes_price = yes_price / 100\n')
code.append('            if yes_price <= 0 or yes_price >= 1:\n')
code.append('                yes_price = 0.5\n')
code.append('            ticker = raw.get("ticker", "unknown")\n')
code.append('            kalshi_url = "https://kalshi.com/markets/" + ticker\n')
code.append('            return {\n')
code.append('                "id": ticker,\n')
code.append('                "question": raw.get("title", "Unknown"),\n')
code.append('                "description": "",\n')
code.append('                "market_type": "binary",\n')
code.append('                "outcomes": [{"name": "Yes", "price": yes_price}, {"name": "No", "price": round(1 - yes_price, 4)}],\n')
code.append('                "volume": float(raw.get("volume_fp", 0) or 0),\n')
code.append('                "liquidity": float(raw.get("liquidity_dollars", 0) or 0),\n')
code.append('                "days_to_resolve": self._days_until(raw.get("close_time", "")),\n')
code.append('                "category": raw.get("event_ticker", "General"),\n')
code.append('                "url": kalshi_url\n')
code.append('            }\n')
code.append('        except Exception:\n')
code.append('            return None\n')
code.append('\n')
code.append('    def place_order(self, ticker, side, amount_usd, dry_run=True):\n')
code.append('        if dry_run:\n')
code.append('            print("[PAPER] Would bet $" + str(amount_usd))\n')
code.append('            return {"status": "paper", "ticker": ticker, "side": side, "amount": amount_usd}\n')
code.append('        path = "/portfolio/orders"\n')
code.append('        try:\n')
code.append('            resp = self.session.post(self.BASE_URL + path, headers=self._sign_request("POST", path), json={"ticker": ticker, "side": side, "type": "market", "count": int(amount_usd)}, timeout=15)\n')
code.append('            resp.raise_for_status()\n')
code.append('            return resp.json()\n')
code.append('        except Exception as e:\n')
code.append('            print("Error: " + str(e))\n')
code.append('            return None\n')
code.append('\n')
code.append('    def _days_until(self, date_str):\n')
code.append('        if not date_str:\n')
code.append('            return 999\n')
code.append('        try:\n')
code.append('            end = datetime.fromisoformat(date_str.replace("Z", "+00:00"))\n')
code.append('            return max(0, (end - datetime.now(timezone.utc)).days)\n')
code.append('        except Exception:\n')
code.append('            return 999\n')
code.append('\n')
code.append('    def _demo_markets(self):\n')
code.append('        return [\n')
code.append('            {"id": "DEMO-001", "question": "Will SP500 close above 5000 today?", "description": "", "market_type": "binary", "outcomes": [{"name": "Yes", "price": 0.62}, {"name": "No", "price": 0.38}], "volume": 50000, "liquidity": 25000, "days_to_resolve": 1, "category": "Financials", "url": "https://kalshi.com/demo"},\n')
code.append('            {"id": "DEMO-002", "question": "Will Bitcoin be above 80000 today?", "description": "", "market_type": "binary", "outcomes": [{"name": "Yes", "price": 0.44}, {"name": "No", "price": 0.56}], "volume": 80000, "liquidity": 40000, "days_to_resolve": 1, "category": "Crypto", "url": "https://kalshi.com/demo"}\n')
code.append('        ]\n')

with open(path, 'w', encoding='utf-8') as f:
    f.writelines(code)

import os
print("Done! Size: " + str(os.path.getsize(path)) + " bytes")